### PR TITLE
Update meta.yaml to remove s3fs<2024 pin

### LINKED ISSUE #38: remove `s3fs<2024` pin
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The meta.yaml contains a pin of `s3fs<2024`:
https://github.com/conda-forge/earthdata-feedstock/blob/main/recipe/meta.yaml#L30
 but I don't think this is actually a requirement and it's preventing environments from building properly since we are now at `s3fs=2024.2.0`

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

### PR DESCRIPTION
**Pull request by rsignell**
fixes #38

### CODE REVIEW

**Comment by betolink** [comment]
@rsignell I guess we need to do a new release and unpin s3fs there too, cc @jhkennedy

**Comment by mfisher87** [comment]
TODO:

- [ ] Remove `<2024` pin from `pyproject.toml`
- [ ] Release
- [ ] Update this PR to specify newly-released version number and sha

**Review by betolink — APPROVED** [review]

**Comment by mfisher87** [comment]
@betolink wasn't quite ready :) I think we're going to get a build failure because we didn't bump the version or build number in this PR.

**Comment by betolink** [comment]
@mfisher87 I wasn't expecting a successful build, just wanted to merge before the v0.9.0 PR comes.

**Comment by mfisher87** [comment]
I just figured we'd do all that in this PR :)

**Pull request merged**
